version = 1
SPDX-PackageName = "forza-motorsport-linux-tools"
SPDX-PackageSupplier = "volcmen"
SPDX-PackageDownloadLocation = "NOASSERTION"

[[annotations]]
path = [
    ".github/**",
    ".gitignore",
    "README.md",
    "bin/**",
    "config/**",
    "docs/**",
    "justfile",
    "manifests/**",
    "pyproject.toml",
    "scripts/**",
    "tests/**",
    "tools/**",
]
SPDX-FileCopyrightText = "2026 volcmen"
SPDX-License-Identifier = "GPL-3.0-or-later"
