#!/usr/bin/env bash

set -u

if [[ -n ${FORZA_TEST_ROOT:-} ]]; then
    home_root=$FORZA_TEST_ROOT
else
    home_root=${HOME:?HOME is required}
fi

if [[ -v FORZA_TEST_UID ]]; then
    uid=$FORZA_TEST_UID
else
    uid=$(id -u)
fi
if [[ ! $uid =~ ^[0-9]+$ ]]; then
    printf 'error: numeric UID required\n' >&2
    exit 2
fi
launcher="$home_root/.local/bin/forza-linux"
printf -v quoted_launcher '%q' "$launcher"

printf 'WINEDLLOVERRIDES=xgameruntime=b PRESSURE_VESSEL_FILESYSTEMS_RW=/run/user/%s/xodus.sock %s %%command%%\n' \
    "$uid" "$quoted_launcher"
